### ISSUE TITLE
VLC can not play hls

### ISSUE THREAD

**Issue by coolqiu** [dengxiayehu/flvpusher#2]
./flvpusher -i ./bd1.mp4 --hls_playlist html/omn/omn3u8 --hls_time 10 -w , but vlc http://192.168.1.68:9877/omn/omn.m3u8 do not working

**Comment by dengxiayehu** [comment]
Try:
Step 1
$ flvpusher -i ./bd1.mp4 --hls_playlist html/omn/omn.m3u8 --hls_time 10

Step 2
$ flvpusher -w

Step 3
Use vlc to play "http://your-ip-address:9877/omn/omn.m3u8"

Note: 
Video format is h264, and audio format is aac.
